### ISSUE TITLE
Could not make after java update

### ISSUE THREAD

**Issue by kosatchev** [activityworkshop/GpsPrune#17]
I tried to make the program after updating java and got an error:
gpsprune version is 18.6 and 19.
```
Exception in thread "main" java.util.MissingResourceException: Can't find bundle for base name tim.prune.lang.prune-texts, locale en_GB
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:845)
	at tim.prune.I18nManager.init(I18nManager.java:38)
	at tim.prune.GpsPrune.main(GpsPrune.java:135)
/home/user/.cache/netbeans/8.2/executor-snippets/run.xml:53: Java returned: 1
```

**Comment by kosatchev** [comment]
I just re-downloaded latest version from this website and it worked
