### ISSUE TITLE
gpsprune 20 fails to start (Exception in thread "main" java.util.MissingResourceException: Can't find bundle for base name tim.prune.lang.prune-texts, locale en_GB)

### ISSUE THREAD

**Issue by sebastic** [activityworkshop/GpsPrune#23]
The gpsprune Debian package was updated to version 20, but it fails to start:
```
$ bash -x /usr/bin/gpsprune 
+ PRUNEJAR=/usr/share/gpsprune/gpsprune.jar
+ JAVA_OPTS=' -Djava.net.preferIPv4Stack=true'
++ echo
++ sed -n 's?http[s|]://\([^:/]\+\).*?\1?p'
+ proxyhost=
++ echo
++ sed -n 's?http[s|]://[^:]\+:\([0-9]\+\).*?\1?p'
+ proxyport=
+ '[' -z ']'
+ '[' -z ']'
+ java -Djava.net.preferIPv4Stack=true -jar /usr/share/gpsprune/gpsprune.jar
Exception in thread "main" java.util.MissingResourceException: Can't find bundle for base name tim.prune.lang.prune-texts, locale en_GB
        at java.base/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2055)
        at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1689)
        at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1593)
        at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1556)
        at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:932)
        at tim.prune.I18nManager.init(I18nManager.java:38)
        at tim.prune.GpsPrune.main(GpsPrune.java:137)
```

There is indeed no `en_GB` properties file in the source tree:
```
$ ls -l tim/prune/lang/prune-texts_*
-rw-r--r-- 1 bas bas  36320 Mar 30 05:36 tim/prune/lang/prune-texts_af.properties
-rw-r--r-- 1 bas bas   2263 Mar 30 05:36 tim/prune/lang/prune-texts_cy.properties
-rw-r--r-- 1 bas bas  44729 Mar 30 05:36 tim/prune/lang/prune-texts_cz.properties
-rw-r--r-- 1 bas bas   2805 Mar 30 05:36 tim/prune/lang/prune-texts_da.properties
-rw-r--r-- 1 bas bas  43586 Mar 30 05:36 tim/prune/lang/prune-texts_de_CH.properties
-rw-r--r-- 1 bas bas  43367 Mar 30 05:36 tim/prune/lang/prune-texts_de.properties
-rw-r--r-- 1 bas bas  39609 Mar 30 05:36 tim/prune/lang/prune-texts_en.properties
-rw-r--r-- 1 bas bas    811 Mar 30 05:36 tim/prune/lang/prune-texts_en_US.properties
-rw-r--r-- 1 bas bas  42679 Mar 30 05:36 tim/prune/lang/prune-texts_es.properties
-rw-r--r-- 1 bas bas   4940 Aug 31  2018 tim/prune/lang/prune-texts_fa.properties
-rw-r--r-- 1 bas bas  43358 Mar 30 05:36 tim/prune/lang/prune-texts_fi.properties
-rw-r--r-- 1 bas bas  42227 Mar 30 05:36 tim/prune/lang/prune-texts_fr.properties
-rw-r--r-- 1 bas bas  51520 Mar 30 05:36 tim/prune/lang/prune-texts_hu.properties
-rw-r--r-- 1 bas bas   2827 Aug 31  2018 tim/prune/lang/prune-texts_in.properties
-rw-r--r-- 1 bas bas  42047 Mar 30 05:36 tim/prune/lang/prune-texts_it.properties
-rw-r--r-- 1 bas bas  44746 Mar 30 05:36 tim/prune/lang/prune-texts_ja.properties
-rw-r--r-- 1 bas bas  42186 Mar 30 05:36 tim/prune/lang/prune-texts_ko.properties
-rw-r--r-- 1 bas bas  41450 Mar 30 05:36 tim/prune/lang/prune-texts_nl.properties
-rw-r--r-- 1 bas bas   4602 Mar 30 05:36 tim/prune/lang/prune-texts_no.properties
-rw-r--r-- 1 bas bas  45118 Mar 30 05:36 tim/prune/lang/prune-texts_pl.properties
-rw-r--r-- 1 bas bas  40833 Mar 30 05:36 tim/prune/lang/prune-texts_pt.properties
-rw-r--r-- 1 bas bas  44732 Mar 30 05:36 tim/prune/lang/prune-texts_ro.properties
-rw-r--r-- 1 bas bas 118207 Mar 30 05:36 tim/prune/lang/prune-texts_ru.properties
-rw-r--r-- 1 bas bas  18474 Mar 30 05:36 tim/prune/lang/prune-texts_sv.properties
-rw-r--r-- 1 bas bas  17231 Mar 30 05:36 tim/prune/lang/prune-texts_tr.properties
-rw-r--r-- 1 bas bas  27628 Mar 30 05:36 tim/prune/lang/prune-texts_uk.properties
-rw-r--r-- 1 bas bas  45917 Mar 30 05:36 tim/prune/lang/prune-texts_zh.properties
```

These files were included in 19.2:
```
$ jar -tvf usr/share/gpsprune/gpsprune.jar | grep -Ec "tim/prune/lang/prune-texts_[a-zA-Z_]*.properties"
26
```
But not in 20:
```
$ jar -tvf /usr/share/gpsprune/gpsprune.jar | grep -Ec "tim/prune/lang/prune-texts_[a-zA-Z_]*.properties"
0
```

**Comment by sebastic** [comment]
This turns out to be a bug in javahelper: [Debia Bug #945917 - jh_build: JH_JAR_EXTRA is ignored](https://bugs.debian.org/945917)
