### ISSUE TITLE
java runtime requirements (UnsupportedClassVersionError)

### ISSUE THREAD

**Issue by danadam** [activityworkshop/GpsPrune#24]
In several places on https://activityworkshop.net it says that required java version is 1.5:
* [gpsprune](https://activityworkshop.net/software/gpsprune/index.html): Tested java versions run from Sun 1.5 to OpenJdk 9.
* [Problem-solving](https://activityworkshop.net/software/gpsprune/problem-solving.html): GpsPrune requires at least version 1.5 of java to run, ...
* [Dependencies](https://activityworkshop.net/software/gpsprune/dependencies.html): To run GpsPrune you need to get a java runtime of at least version 1.5, ...

In another place it says 1.6:
* [gpsprune](https://activityworkshop.net/software/gpsprune/index.html): Java runtime of at least version 1.6 including Swing libraries.

The actual required java version with gpsprune 20 downloaded from [Download](https://activityworkshop.net/software/gpsprune/download.html) seems to be java 9:
```
]$ java -jar gpsprune_20.jar
Error: A JNI error has occurred, please check your installation and try again                                                              
Exception in thread "main" java.lang.UnsupportedClassVersionError: tim/prune/GpsPrune has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)                                                                               
        at java.lang.ClassLoader.defineClass(ClassLoader.java:757)                                                                         
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)                                                         
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)                                                                    
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)                                                                      
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)                                                                          
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)                                                                          
        at java.security.AccessController.doPrivileged(Native Method)                                                                      
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)                                                                      
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419)                                                                           
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)                                                                   
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)                                                                           
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
]$ java -version                                                                                                             
openjdk version "1.8.0_242"                                                                                                                
OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-0ubuntu3~18.04-b08)                                                                 
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
```

**Comment by activityworkshop** [comment]
You're right, thanks for the feedback.
The mentions of Java1.5 are an oversight from the previous version of GpsPrune, which did indeed compile and run with Java1.5.  In order to remove some ugly and presumably unnecessary reflection, the requirement for compilation and running is now 1.6.

The jar published on the downloads page was compiled to be compatible with Java 9, which is already several years old so I'm surprised you're getting such an error.  Compiling it yourself should solve that problem for you.
Would it help if I also published a Java6-compatible binary, or would it be clearer to change the descriptions to say a minimum of Java9 is required?  I'm curious how common Java 8 still is?

**Comment by mprins** [comment]
Java 8 "is here to stay" until at least May 2026 in the form of OpenJDK, see https://access.redhat.com/articles/1299013

Java 9 has been EOL for a while now, it was never meant to be around for long.

You should set the `target` option on the java compiler; it's unclear to me how you build the jar file as there are both Ant and shell scripts and and gradle and manev and...,
for  `javac` add `-target 8`, for Maven you seem covered as it has the property `maven.compiler.target` set. I have no idea about the others.

I would like to suggest to stick to java 8 compatibility for some time as this is the earliest "Long Term Edition" (java 11 being the next LTE)

**Comment by activityworkshop** [comment]
Could you please try again with https://gpsprune.activityworkshop.net/gpsprune_20_java6.jar ?

I thought that java 9 was a safe minimum requirement, as even Ubuntu 16.04 has it, but I can see that there might be even older systems out there which haven't been updated.  Does this solve your problem?

**Comment by danadam** [comment]
Yes, that works.

On this particular machine I'm using Ubuntu 18.04 with openjdk 8 installed because "reasons". I don't mind if pre-build jar requires java 9, but I just thought that the requirements should be clearly stated there there at the download page.

**Comment by activityworkshop** [comment]
Ok, I totally understand.  With the 6+ version it sounds like your problem is solved, so I'll close this issue.  We'll revisit this with the next release, no doubt.
