### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by pykereaper** [activityworkshop/GpsPrune#76]
The new version 23 won't start when I compile it with Gradle.

Stacktrace:
```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.net.URL.toExternalForm()" because "location" is null
        at java.desktop/javax.swing.ImageIcon.<init>(ImageIcon.java:234)
        at tim.prune.gui.IconManager.getImageIcon(IconManager.java:75)
        at tim.prune.gui.MenuManager.makeToolbarButton(MenuManager.java:736)
        at tim.prune.gui.MenuManager.createToolBar(MenuManager.java:674)
        at tim.prune.GpsPrune.launch(GpsPrune.java:200)
        at tim.prune.GpsPrune.main(GpsPrune.java:160)
```

Problem is, that you added some new resource files (images) in `tim/prune/gui/images/toolbar`. Previously, all images were inside the `.../images` folder, where now there are subdirectories.

The Gradle build file has to define where Java resources are inside the project. In case of the `images` directory, the line looks like this:
```kotlin
        resources.include(
                "tim/prune/gui/images/*",
                ...
        }
```

The single asterisk only applies to all files inside the directory. In order to work with subdirectories, it has to be a double asterisk: `.../images/** `

I'll provide a pull request to fix this issue.

PS: I think the same issue applies to the  `pom.xml` for the Maven build. But I'm not using Maven, so I'm not 100% sure.

**Comment by activityworkshop** [comment]
Great!
Thanks for the patch, and especially for the explanation :)
